// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbSB-mIDPjklukNTRcoJtRX_xWBM1S9PU',
    appId: '1:335551343963:web:2561f98ad638045e3b7e7e',
    messagingSenderId: '335551343963',
    projectId: 'kps-mobile-app-flutter',
    authDomain: 'kps-mobile-app-flutter.firebaseapp.com',
    storageBucket: 'kps-mobile-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwCA09BSqVZm4OexOfeQswYWD9ZczUidA',
    appId: '1:335551343963:android:dec37d43ce80782c3b7e7e',
    messagingSenderId: '335551343963',
    projectId: 'kps-mobile-app-flutter',
    storageBucket: 'kps-mobile-app-flutter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSZV-89SS8TyR7gyBl4_vYh-PB2HZsI4',
    appId: '1:335551343963:ios:035cab0d28c328dc3b7e7e',
    messagingSenderId: '335551343963',
    projectId: 'kps-mobile-app-flutter',
    storageBucket: 'kps-mobile-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.smallAppFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSZV-89SS8TyR7gyBl4_vYh-PB2HZsI4',
    appId: '1:335551343963:ios:035cab0d28c328dc3b7e7e',
    messagingSenderId: '335551343963',
    projectId: 'kps-mobile-app-flutter',
    storageBucket: 'kps-mobile-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.smallAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbSB-mIDPjklukNTRcoJtRX_xWBM1S9PU',
    appId: '1:335551343963:web:ec991131633199423b7e7e',
    messagingSenderId: '335551343963',
    projectId: 'kps-mobile-app-flutter',
    authDomain: 'kps-mobile-app-flutter.firebaseapp.com',
    storageBucket: 'kps-mobile-app-flutter.firebasestorage.app',
  );
}
