// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjdQKVk7zfHR4slC2LaUNlKY1fNGCrAw',
    appId: '1:531273892536:web:e27b8445449074eedc6a4d',
    messagingSenderId: '531273892536',
    projectId: 'app-flutter-17067',
    authDomain: 'app-flutter-17067.firebaseapp.com',
    storageBucket: 'app-flutter-17067.firebasestorage.app',
    measurementId: 'G-ZB982EV5XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHrVO_10mSPt6hbzY4eMNUTWPa6w_rKM',
    appId: '1:531273892536:android:7f53ce2495121768dc6a4d',
    messagingSenderId: '531273892536',
    projectId: 'app-flutter-17067',
    storageBucket: 'app-flutter-17067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3tzc1es6qLRPTwof2C9zaq8fUW3GA0pI',
    appId: '1:531273892536:ios:274c5908c70510aadc6a4d',
    messagingSenderId: '531273892536',
    projectId: 'app-flutter-17067',
    storageBucket: 'app-flutter-17067.firebasestorage.app',
    iosBundleId: 'com.example.smallAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3tzc1es6qLRPTwof2C9zaq8fUW3GA0pI',
    appId: '1:531273892536:ios:274c5908c70510aadc6a4d',
    messagingSenderId: '531273892536',
    projectId: 'app-flutter-17067',
    storageBucket: 'app-flutter-17067.firebasestorage.app',
    iosBundleId: 'com.example.smallAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjdQKVk7zfHR4slC2LaUNlKY1fNGCrAw',
    appId: '1:531273892536:web:4767919bb5090615dc6a4d',
    messagingSenderId: '531273892536',
    projectId: 'app-flutter-17067',
    authDomain: 'app-flutter-17067.firebaseapp.com',
    storageBucket: 'app-flutter-17067.firebasestorage.app',
    measurementId: 'G-JY9W0LQCTH',
  );
}
